#!/bin/sh
SITES_DIR=/usr/share/nginx/html
mkdir -p $SITES_DIR
GIT_AUTH=""
if [ -n "$GITHUB_TOKEN" ]; then
  GIT_AUTH="${GI...
fi
REPOS="""
100percentlockus|100percentlockus.com|
123locksmith|ngg80c8kkoc040wc4w4ow4o4.shlomoholdingsservicesllc.com|
247keyexpress|247keyexpress.com|
airbnblockus|airbnblockus.com|
airportlockus|airportlockus.com|
amazonlockus|amazonlockus.com|
applelockus|applelockus.com|
banklockus|banklockus.com|
bestlockdealus|bestlockdealus.com|
bestlockeverus|bestlockeverus.com|
bmwlockus|bmwlockus.com|
bypasslockus|bypasslockus.com|
carkeysmasters|carkeysmasters.com|
cityhalllockus|cityhalllockus.com|
citykeyservice|citykeyservice.com|
citylockus|citylockus.com|
cracklockus|cracklockus.com|
cryptolockus|cryptolockus.com|
deeplockus|deeplockus.com|
doorlockace|doorlockace.com|
doorlockbay|doorlockbay.com|
doorlockbox|doorlockbox.com|
doorlockfit|doorlockfit.com|
doorlockhq|doorlockhq.com|
doorlocklab|doorlocklab.com|
doorlocklux|doorlocklux.com|
doorlockmaxx|doorlockmaxx.com|
doorlockops|doorlockops.com|
doorlockprox|doorlockprox.com|
doorlockrun|doorlockrun.com|
doorlocksky|doorlocksky.com|
doorlocktap|doorlocktap.com|
doorlockway|doorlockway.com|
doorlockzap|doorlockzap.com|
doorlockzen|doorlockzen.com|
doorlockzip|doorlockzip.com|
emergencyauthoritylock|emergencyauthoritylock.com|
emergencylockus|emergencylockus.com|
everylockus|everylockus.com|
fastcheaplockus|fastcheaplockus.com|
fastkeyresponse|fastkeyresponse.com|
federalaccesslock|federalaccesslock.com|
federallockus|federallockus.com|
forcelockus|forcelockus.com|
fordlockus|fordlockus.com|
freelockserviceus|freelockserviceus.com|
freelockus|freelockus.com|
govlockservices|govlockservices.com|
guaranteedlockus|guaranteedlockus.com|
hacklockus|hacklockus.com|
hardlockus|hardlockus.com|
hondalockus|hondalockus.com|
hotlockus|hotlockus.com|
illegallockus|illegallockus.com|
instantlocknowus|instantlocknowus.com|
keycrewamerica|keycrewamerica.com|
keyelementservice|keyelementservice.com|
keyexpressus|keyexpressus.com|
keyforgedirect|keyforgedirect.com|
keyguardservice|keyguardservice.com|
keyhiveusa|keyhiveusa.com|
keyhouseusa|keyhouseusa.com|
keymasterpros|keymasterpros.com|
keymatrixservice|keymatrixservice.com|
keymobileteam|keymobileteam.com|
keypointsolutionsus|keypointsolutionsus.com|
keyprotectiongroup|keyprotectiongroup.com|
keyrepairexperts|keyrepairexperts.com|
keyrescuecentral|keyrescuecentral.com|
keyrescueguys|keyrescueguys.com|
keysbrothers|keysbrothers.com|
keyschampion|keyschampion.com|
keyscrewus|keyscrewus.com|
keysdepotus|keysdepotus.com|
keysforce|keysforce.com|
keysgeniususa|keysgeniususa.com|
keysgurus|keysgurus.com|
keysheroes|keysheroes.com|
keyshieldus|keyshieldus.com|
keyshubus|keyshubus.com|
keysmedicus|keysmedicus.com|
keyspartnersus|keyspartnersus.com|
keyspatrolus|keyspatrolus.com|
keyspioneer|keyspioneer.com|
keysprecision|keysprecision.com|
keysprintassist|keysprintassist.com|
keyspros|keyspros.com|
keysquadus|keysquadus.com|
keysquadusa|keysquadusa.com|
keysresponders|keysresponders.com|
keysriders|keysriders.com|
keystationus|keystationus.com|
keystechnicians|keystechnicians.com|
keystormus|keystormus.com|
keytechexperts|gko4c888ck00cw8kc0s0gsc8.shlomoholdingsservicesllc.com|
keyurgentcrew|keyurgentcrew.com|
lockandkey24|lockandkey24.com|
lockandkey247|lockandkey247.com|
lockandkey247call|lockandkey247call.com|
lockandkey247fix|lockandkey247fix.com|
lockandkey247go|lockandkey247go.com|
lockandkey247help|lockandkey247help.com|
lockandkey247now|lockandkey247now.com|
lockandkey247pro|lockandkey247pro.com|
lockandkey247service|lockandkey247service.com|
lockandkey247x|lockandkey247x.com|
lockandkey24call|lockandkey24call.com|
lockandkey24fix|lockandkey24fix.com|
lockandkey24go|lockandkey24go.com|
lockandkey24help|lockandkey24help.com|
lockandkey24now|lockandkey24now.com|
lockandkey24pro|lockandkey24pro.com|
lockandkey24x7|lockandkey24x7.com|
lockandkey4u|lockandkey4u.com|
lockandkeyaccess|lockandkeyaccess.com|
lockandkeyaccess247|lockandkeyaccess247.com|
lockandkeyaccessnow|lockandkeyaccessnow.com|
lockandkeyaccesspro|lockandkeyaccesspro.com|
lockandkeyaccessy|lockandkeyaccessy.com|
lockandkeyace|lockandkeyace.com|
lockandkeyace24x|lockandkeyace24x.com|
lockandkeyacex|lockandkeyacex.com|
lockandkeyadvance|lockandkeyadvance.com|
lockandkeyaffordable|lockandkeyaffordable.com|
lockandkeyaidnow|lockandkeyaidnow.com|
lockandkeyaidx|lockandkeyaidx.com|
lockandkeyall|lockandkeyall.com|
lockandkeyallaccess|lockandkeyallaccess.com|
lockandkeyallservices|lockandkeyallservices.com|
lockandkeyallx|lockandkeyallx.com|
lockandkeyanytime|lockandkeyanytime.com|
lockandkeyarea|lockandkeyarea.com|
lockandkeyaro|lockandkeyaro.com|
lockandkeyaro24|lockandkeyaro24.com|
lockandkeyassist|lockandkeyassist.com|
lockandkeyauthority|lockandkeyauthority.com|
lockandkeyauto|lockandkeyauto.com|
lockandkeyauto247|lockandkeyauto247.com|
lockandkeyauto24x|lockandkeyauto24x.com|
lockandkeyautofix|lockandkeyautofix.com|
lockandkeyautogo|lockandkeyautogo.com|
lockandkeyautohome|lockandkeyautohome.com|
lockandkeyautox|lockandkeyautox.com|
lockandkeybasex|lockandkeybasex.com|
lockandkeybolt|lockandkeybolt.com|
lockandkeyboltpro|lockandkeyboltpro.com|
lockandkeyboltx|lockandkeyboltx.com|
lockandkeycall|lockandkeycall.com|
lockandkeycall247|lockandkeycall247.com|
lockandkeycall24x|lockandkeycall24x.com|
lockandkeycallfast|lockandkeycallfast.com|
lockandkeycallgox|lockandkeycallgox.com|
lockandkeycallnow|lockandkeycallnow.com|
lockandkeycallnow247|lockandkeycallnow247.com|
lockandkeycallx|lockandkeycallx.com|
lockandkeycare|lockandkeycare.com|
lockandkeycentral|lockandkeycentral.com|
lockandkeycentralfix|lockandkeycentralfix.com|
lockandkeycentralgo|lockandkeycentralgo.com|
lockandkeycertified|lockandkeycertified.com|
lockandkeycity|lockandkeycity.com|
lockandkeycityfix|lockandkeycityfix.com|
lockandkeycitygo|lockandkeycitygo.com|
lockandkeycitypros|lockandkeycitypros.com|
lockandkeycommercial|lockandkeycommercial.com|
lockandkeycompany|lockandkeycompany.com|
lockandkeycomplete|lockandkeycomplete.com|
lockandkeycore|lockandkeycore.com|
lockandkeycorego|lockandkeycorego.com|
lockandkeycorenow|lockandkeycorenow.com|
lockandkeycorex|lockandkeycorex.com|
lockandkeycrew|lockandkeycrew.com|
lockandkeydash24x|lockandkeydash24x.com|
lockandkeydashgo|lockandkeydashgo.com|
lockandkeydashx|lockandkeydashx.com|
lockandkeydirect|lockandkeydirect.com|
lockandkeydirectnow|lockandkeydirectnow.com|
lockandkeydoor|lockandkeydoor.com|
lockandkeydoor247|lockandkeydoor247.com|
lockandkeydoor24x|lockandkeydoor24x.com|
lockandkeydoorfix|lockandkeydoorfix.com|
lockandkeydoorgo|lockandkeydoorgo.com|
lockandkeydoorpro|lockandkeydoorpro.com|
lockandkeydoorsy|lockandkeydoorsy.com|
lockandkeydoorx|lockandkeydoorx.com|
lockandkeyedge|lockandkeyedge.com|
lockandkeyedgego|lockandkeyedgego.com|
lockandkeyedgenow|lockandkeyedgenow.com|
lockandkeyedgex|lockandkeyedgex.com|
lockandkeyelitego|lockandkeyelitego.com|
lockandkeyelitenow|lockandkeyelitenow.com|
lockandkeyelitepros|lockandkeyelitepros.com|
lockandkeyeliteservices|lockandkeyeliteservices.com|
lockandkeyemergency|lockandkeyemergency.com|
lockandkeyemergency247|lockandkeyemergency247.com|
lockandkeyemergencyfix|lockandkeyemergencyfix.com|
lockandkeyemergencynow|lockandkeyemergencynow.com|
lockandkeyemergencypro|lockandkeyemergencypro.com|
lockandkeyemergencyservices|lockandkeyemergencyservices.com|
lockandkeyentry|lockandkeyentry.com|
lockandkeyentry247|lockandkeyentry247.com|
lockandkeyentrynow|lockandkeyentrynow.com|
lockandkeyentrypro|lockandkeyentrypro.com|
lockandkeyentrypros|lockandkeyentrypros.com|
lockandkeyentryx|lockandkeyentryx.com|
lockandkeyero|lockandkeyero.com|
lockandkeyexpertslocal|lockandkeyexpertslocal.com|
lockandkeyexpertspro|lockandkeyexpertspro.com|
lockandkeyexpertsusa|lockandkeyexpertsusa.com|
lockandkeyexpress|lockandkeyexpress.com|
lockandkeyexpressgo|lockandkeyexpressgo.com|
lockandkeyexpressnow|lockandkeyexpressnow.com|
lockandkeyfast|lockandkeyfast.com|
lockandkeyfast247|lockandkeyfast247.com|
lockandkeyfast24x|lockandkeyfast24x.com|
lockandkeyfastaid|lockandkeyfastaid.com|
lockandkeyfastfix|lockandkeyfastfix.com|
lockandkeyfastgo|lockandkeyfastgo.com|
lockandkeyfastnow|lockandkeyfastnow.com|
lockandkeyfasto|lockandkeyfasto.com|
lockandkeyfastresponse|lockandkeyfastresponse.com|
lockandkeyfastservice|lockandkeyfastservice.com|
lockandkeyfastx|lockandkeyfastx.com|
lockandkeyfire24x|lockandkeyfire24x.com|
lockandkeyfirex|lockandkeyfirex.com|
lockandkeyfirst|lockandkeyfirst.com|
lockandkeyfirstnow|lockandkeyfirstnow.com|
lockandkeyfix|lockandkeyfix.com|
lockandkeyfix24|lockandkeyfix24.com|
lockandkeyfix24x|lockandkeyfix24x.com|
lockandkeyfixfast|lockandkeyfixfast.com|
lockandkeyfixgox|lockandkeyfixgox.com|
lockandkeyfixnow|lockandkeyfixnow.com|
lockandkeyfixpro|lockandkeyfixpro.com|
lockandkeyfixx|lockandkeyfixx.com|
lockandkeyflex24x|lockandkeyflex24x.com|
lockandkeyflexx|lockandkeyflexx.com|
lockandkeyforce|lockandkeyforce.com|
lockandkeyforcepro|lockandkeyforcepro.com|
lockandkeygate24x|lockandkeygate24x.com|
lockandkeygatex|lockandkeygatex.com|
lockandkeygen|lockandkeygen.com|
lockandkeygo|lockandkeygo.com|
lockandkeygo24|lockandkeygo24.com|
lockandkeygo247|lockandkeygo247.com|
lockandkeygo24x|lockandkeygo24x.com|
lockandkeygofast|lockandkeygofast.com|
lockandkeygonow|lockandkeygonow.com|
lockandkeygox|lockandkeygox.com|
lockandkeygripx|lockandkeygripx.com|
lockandkeygroup|lockandkeygroup.com|
lockandkeyguard|lockandkeyguard.com|
lockandkeyguard247|lockandkeyguard247.com|
lockandkeyguardnow|lockandkeyguardnow.com|
lockandkeyguardpro|lockandkeyguardpro.com|
lockandkeyguardx|lockandkeyguardx.com|
lockandkeyguardy|lockandkeyguardy.com|
lockandkeyhelp|lockandkeyhelp.com|
lockandkeyhelpfast|lockandkeyhelpfast.com|
lockandkeyhelpnow|lockandkeyhelpnow.com|
lockandkeyhelpx|lockandkeyhelpx.com|
lockandkeyhome247|lockandkeyhome247.com|
lockandkeyhome24x|lockandkeyhome24x.com|
lockandkeyhomeauto|lockandkeyhomeauto.com|
lockandkeyhomefix|lockandkeyhomefix.com|
lockandkeyhomego|lockandkeyhomego.com|
lockandkeyhomex|lockandkeyhomex.com|
lockandkeyhq|lockandkeyhq.com|
lockandkeyhqx|lockandkeyhqx.com|
lockandkeyhub|lockandkeyhub.com|
lockandkeyify|lockandkeyify.com|
lockandkeyify24|lockandkeyify24.com|
lockandkeyimmediate|lockandkeyimmediate.com|
lockandkeyinstall|lockandkeyinstall.com|
lockandkeyinstant|lockandkeyinstant.com|
lockandkeyinstantfix|lockandkeyinstantfix.com|
lockandkeyio|lockandkeyio.com|
lockandkeyiron|lockandkeyiron.com|
lockandkeyiron24x|lockandkeyiron24x.com|
lockandkeyironpro|lockandkeyironpro.com|
lockandkeyironx|lockandkeyironx.com|
lockandkeyivo|lockandkeyivo.com|
lockandkeyixo|lockandkeyixo.com|
lockandkeyjet24x|lockandkeyjet24x.com|
lockandkeyjetgo|lockandkeyjetgo.com|
lockandkeyjetx|lockandkeyjetx.com|
lockandkeykeyfix|lockandkeykeyfix.com|
lockandkeykeypro|lockandkeykeypro.com|
lockandkeykeysy|lockandkeykeysy.com|
lockandkeykeyx|lockandkeykeyx.com|
lockandkeylab|lockandkeylab.com|
lockandkeylatch|lockandkeylatch.com|
lockandkeyliftx|lockandkeyliftx.com|
lockandkeylinkx|lockandkeylinkx.com|
lockandkeylocal|lockandkeylocal.com|
lockandkeylocalfix|lockandkeylocalfix.com|
lockandkeylocalgo|lockandkeylocalgo.com|
lockandkeylocalpros|lockandkeylocalpros.com|
lockandkeylock|lockandkeylock.com|
lockandkeylockfix|lockandkeylockfix.com|
lockandkeylockpro|lockandkeylockpro.com|
lockandkeylocksy|lockandkeylocksy.com|
lockandkeylockx|lockandkeylockx.com|
lockandkeyly|lockandkeyly.com|
lockandkeymasters|lockandkeymasters.com|
lockandkeymax|lockandkeymax.com|
lockandkeymax24x|lockandkeymax24x.com|
lockandkeymaxx|lockandkeymaxx.com|
lockandkeymetro|lockandkeymetro.com|
lockandkeymetrofix|lockandkeymetrofix.com|
lockandkeymetrogo|lockandkeymetrogo.com|
lockandkeymini|lockandkeymini.com|
lockandkeymobile|lockandkeymobile.com|
lockandkeymobilego|lockandkeymobilego.com|
lockandkeymobilenow|lockandkeymobilenow.com|
lockandkeymobilepros|lockandkeymobilepros.com|
lockandkeymodo|lockandkeymodo.com|
lockandkeynation|lockandkeynation.com|
lockandkeynearby|lockandkeynearby.com|
lockandkeynearbyfix|lockandkeynearbyfix.com|
lockandkeynearbygo|lockandkeynearbygo.com|
lockandkeyneighborhood|lockandkeyneighborhood.com|
lockandkeynet|lockandkeynet.com|
lockandkeynetwork|lockandkeynetwork.com|
lockandkeynex|lockandkeynex.com|
lockandkeynow24x|lockandkeynow24x.com|
lockandkeynowx|lockandkeynowx.com|
lockandkeyon|lockandkeyon.com|
lockandkeyoncall|lockandkeyoncall.com|
lockandkeyondemand|lockandkeyondemand.com|
lockandkeyone|lockandkeyone.com|
lockandkeyonex|lockandkeyonex.com|
lockandkeyonfast|lockandkeyonfast.com|
lockandkeyonsite|lockandkeyonsite.com|
lockandkeyonx|lockandkeyonx.com|
lockandkeyora|lockandkeyora.com|
lockandkeypartner|lockandkeypartner.com|
lockandkeypatho|lockandkeypatho.com|
lockandkeypathx|lockandkeypathx.com|
lockandkeyplus|lockandkeyplus.com|
lockandkeypoint|lockandkeypoint.com|
lockandkeypointfix|lockandkeypointfix.com|
lockandkeyprime|lockandkeyprime.com|
lockandkeyprime247|lockandkeyprime247.com|
lockandkeyprimego|lockandkeyprimego.com|
lockandkeyprimenow|lockandkeyprimenow.com|
lockandkeyprimeservices|lockandkeyprimeservices.com|
lockandkeyprimex|lockandkeyprimex.com|
lockandkeypro|lockandkeypro.com|
lockandkeypro24|lockandkeypro24.com|
lockandkeypro247|lockandkeypro247.com|
lockandkeypro24x|lockandkeypro24x.com|
lockandkeyprobase|lockandkeyprobase.com|
lockandkeyprocall|lockandkeyprocall.com|
lockandkeyprocare|lockandkeyprocare.com|
lockandkeyprofast|lockandkeyprofast.com|
lockandkeyprofessionals|lockandkeyprofessionals.com|
lockandkeyprofix|lockandkeyprofix.com|
lockandkeyprogate|lockandkeyprogate.com|
lockandkeyprogo|lockandkeyprogo.com|
lockandkeyprogox|lockandkeyprogox.com|
lockandkeyprohelp|lockandkeyprohelp.com|
lockandkeyprohub|lockandkeyprohub.com|
lockandkeyprokey|lockandkeyprokey.com|
lockandkeypromax|lockandkeypromax.com|
lockandkeypronow|lockandkeypronow.com|
lockandkeyproone|lockandkeyproone.com|
lockandkeypropath|lockandkeypropath.com|
lockandkeyproplus|lockandkeyproplus.com|
lockandkeypropoint|lockandkeypropoint.com|
lockandkeyproring|lockandkeyproring.com|
lockandkeyproservices|lockandkeyproservices.com|
lockandkeyprospot|lockandkeyprospot.com|
lockandkeyproteam|lockandkeyproteam.com|
lockandkeyproway|lockandkeyproway.com|
lockandkeyproxi|lockandkeyproxi.com|
lockandkeyproz|lockandkeyproz.com|
lockandkeyprozone|lockandkeyprozone.com|
lockandkeyquick|lockandkeyquick.com|
lockandkeyquickfix|lockandkeyquickfix.com|
lockandkeyquickgo|lockandkeyquickgo.com|
lockandkeyquickx|lockandkeyquickx.com|
lockandkeyrapid|lockandkeyrapid.com|
lockandkeyrapid247|lockandkeyrapid247.com|
lockandkeyrapidgo|lockandkeyrapidgo.com|
lockandkeyrapidnow|lockandkeyrapidnow.com|
lockandkeyrapidresponse|lockandkeyrapidresponse.com|
lockandkeyrapidservice|lockandkeyrapidservice.com|
lockandkeyreliable|lockandkeyreliable.com|
lockandkeyreliablego|lockandkeyreliablego.com|
lockandkeyreliablenow|lockandkeyreliablenow.com|
lockandkeyrepair|lockandkeyrepair.com|
lockandkeyrescue247|lockandkeyrescue247.com|
lockandkeyrescuenow|lockandkeyrescuenow.com|
lockandkeyresidential|lockandkeyresidential.com|
lockandkeyresponse|lockandkeyresponse.com|
lockandkeyresponse247|lockandkeyresponse247.com|
lockandkeyresponsenow|lockandkeyresponsenow.com|
lockandkeyresponsepros|lockandkeyresponsepros.com|
lockandkeyresponseteam|lockandkeyresponseteam.com|
lockandkeyresq|lockandkeyresq.com|
lockandkeyringx|lockandkeyringx.com|
lockandkeyrushnow|lockandkeyrushnow.com|
lockandkeyrushx|lockandkeyrushx.com|
lockandkeysafe|lockandkeysafe.com|
lockandkeysafe247|lockandkeysafe247.com|
lockandkeysafefix|lockandkeysafefix.com|
lockandkeysafego|lockandkeysafego.com|
lockandkeysafenow|lockandkeysafenow.com|
lockandkeysafepro|lockandkeysafepro.com|
lockandkeysafety|lockandkeysafety.com|
lockandkeysafex|lockandkeysafex.com|
lockandkeysecure|lockandkeysecure.com|
lockandkeysecure247|lockandkeysecure247.com|
lockandkeysecurego|lockandkeysecurego.com|
lockandkeysecurenow|lockandkeysecurenow.com|
lockandkeysecurenow247|lockandkeysecurenow247.com|
lockandkeysecurepro|lockandkeysecurepro.com|
lockandkeysecuresolutions|lockandkeysecuresolutions.com|
lockandkeysecurex|lockandkeysecurex.com|
lockandkeysecurexus|lockandkeysecurexus.com|
lockandkeysecuritypros|lockandkeysecuritypros.com|
lockandkeyservicehub|lockandkeyservicehub.com|
lockandkeyservicenow|lockandkeyservicenow.com|
lockandkeyservicepros|lockandkeyservicepros.com|
lockandkeyservix|lockandkeyservix.com|
lockandkeyshield|lockandkeyshield.com|
lockandkeyshieldnow|lockandkeyshieldnow.com|
lockandkeyshieldpro|lockandkeyshieldpro.com|
lockandkeysmart|lockandkeysmart.com|
lockandkeysnap|lockandkeysnap.com|
lockandkeysnapgo|lockandkeysnapgo.com|
lockandkeysnapnow|lockandkeysnapnow.com|
lockandkeysnapx|lockandkeysnapx.com|
lockandkeysolid|lockandkeysolid.com|
lockandkeysolidx|lockandkeysolidx.com|
lockandkeysolutionspro|lockandkeysolutionspro.com|
lockandkeysos|lockandkeysos.com|
lockandkeysosnow|lockandkeysosnow.com|
lockandkeysosx|lockandkeysosx.com|
lockandkeysource|lockandkeysource.com|
lockandkeyspotfix|lockandkeyspotfix.com|
lockandkeystar|lockandkeystar.com|
lockandkeystarx|lockandkeystarx.com|
lockandkeysteel|lockandkeysteel.com|
lockandkeysteelpro|lockandkeysteelpro.com|
lockandkeyster|lockandkeyster.com|
lockandkeystrong|lockandkeystrong.com|
lockandkeysupport|lockandkeysupport.com|
lockandkeysurex|lockandkeysurex.com|
lockandkeyswiftgo|lockandkeyswiftgo.com|
lockandkeyswiftx|lockandkeyswiftx.com|
lockandkeysys|lockandkeysys.com|
lockandkeytechs|lockandkeytechs.com|
lockandkeytop|lockandkeytop.com|
lockandkeytotal|lockandkeytotal.com|
lockandkeytrusted|lockandkeytrusted.com|
lockandkeytrustedgo|lockandkeytrustedgo.com|
lockandkeytrustednow|lockandkeytrustednow.com|
lockandkeytrustedpros|lockandkeytrustedpros.com|
lockandkeytrustedservice|lockandkeytrustedservice.com|
lockandkeytrustx|lockandkeytrustx.com|
lockandkeyultimate|lockandkeyultimate.com|
lockandkeyultra|lockandkeyultra.com|
lockandkeyultra247|lockandkeyultra247.com|
lockandkeyultrago|lockandkeyultrago.com|
lockandkeyultranow|lockandkeyultranow.com|
lockandkeyultrax|lockandkeyultrax.com|
lockandkeyunlock|lockandkeyunlock.com|
lockandkeyunlock247|lockandkeyunlock247.com|
lockandkeyunlocknow|lockandkeyunlocknow.com|
lockandkeyunlockpro|lockandkeyunlockpro.com|
lockandkeyunlockr|lockandkeyunlockr.com|
lockandkeyup|lockandkeyup.com|
lockandkeyurban|lockandkeyurban.com|
lockandkeyurbanfix|lockandkeyurbanfix.com|
lockandkeyurbango|lockandkeyurbango.com|
lockandkeyurgent|lockandkeyurgent.com|
lockandkeyurgentfix|lockandkeyurgentfix.com|
lockandkeyvalue|lockandkeyvalue.com|
lockandkeyvault|lockandkeyvault.com|
lockandkeyvault247|lockandkeyvault247.com|
lockandkeyvaultnow|lockandkeyvaultnow.com|
lockandkeyvaultpro|lockandkeyvaultpro.com|
lockandkeyvaultx|lockandkeyvaultx.com|
lockandkeyvaulty|lockandkeyvaulty.com|
lockandkeyworks|lockandkeyworks.com|
lockandkeyx|lockandkeyx.com|
lockandkeyzen|lockandkeyzen.com|
lockandkeyzengo|lockandkeyzengo.com|
lockandkeyzennow|lockandkeyzennow.com|
lockandkeyzenx|lockandkeyzenx.com|
lockandkeyzipgo|lockandkeyzipgo.com|
lockandkeyzipx|lockandkeyzipx.com|
lockandkeyzone|lockandkeyzone.com|
lockandkeyzonefix|lockandkeyzonefix.com|
lockboostcous|qccco0cgw4sg0c8840wck088.shlomoholdingsservicesllc.com|
lockbreakerus|lockbreakerus.com|
lockbusinessus|lockbusinessus.com|
lockcompanyus|lockcompanyus.com|
lockcorpus|lockcorpus.com|
lockcouponsus|lockcouponsus.com|
lockcraftus|lockcraftus.com|
lockcrewxus|lockcrewxus.com|
lockdashcous|lockdashcous.com|
lockdashxus|lockdashxus.com|
lockdeals247us|lockdeals247us.com|
lockdealsus|lockdealsus.com|
lockdenus|lockdenus.com|
lockdiscountus|lockdiscountus.com|
lockdoor24experts|lockdoor24experts.com|
lockdoor24service|lockdoor24service.com|
lockdoor24team|lockdoor24team.com|
lockdooraccess|lockdooraccess.com|
lockdoorace|lockdoorace.com|
lockdooradvance|lockdooradvance.com|
lockdooralliance|lockdooralliance.com|
lockdoorassist|lockdoorassist.com|
lockdoorassistpro|lockdoorassistpro.com|
lockdoorauthority|lockdoorauthority.com|
lockdoorax|lockdoorax.com|
lockdoorband|lockdoorband.com|
lockdoorbarrier|lockdoorbarrier.com|
lockdoorbay|lockdoorbay.com|
lockdoorbee|lockdoorbee.com|
lockdoorbeta|lockdoorbeta.com|
lockdoorbit|lockdoorbit.com|
lockdoorbox|lockdoorbox.com|
lockdoorcentral|lockdoorcentral.com|
lockdoorcommand|lockdoorcommand.com|
lockdoorconnect|lockdoorconnect.com|
lockdoorcore|lockdoorcore.com|
lockdoorcorex|lockdoorcorex.com|
lockdoorcrew|lockdoorcrew.com|
lockdoorcrewx|lockdoorcrewx.com|
lockdoordefense|lockdoordefense.com|
lockdoordepot|lockdoordepot.com|
lockdoordirectpro|lockdoordirectpro.com|
lockdooredge|lockdooredge.com|
lockdooredgepro|lockdooredgepro.com|
lockdoorelite|lockdoorelite.com|
lockdoorexperts|lockdoorexperts.com|
lockdoorexpertshub|lockdoorexpertshub.com|
lockdoorexpertspro|lockdoorexpertspro.com|
lockdoorfit|lockdoorfit.com|
lockdoorfix|lockdoorfix.com|
lockdoorfixers|lockdoorfixers.com|
lockdoorfixpro|lockdoorfixpro.com|
lockdoorfixx|lockdoorfixx.com|
lockdoorflex|lockdoorflex.com|
lockdoorforce|lockdoorforce.com|
lockdoorgearx|lockdoorgearx.com|
lockdoorgo|lockdoorgo.com|
lockdoorgox|lockdoorgox.com|
lockdoorgrid|lockdoorgrid.com|
lockdoorgridx|lockdoorgridx.com|
lockdoorguardian|lockdoorguardian.com|
lockdoorguardx|lockdoorguardx.com|
lockdoorhelpdesk|lockdoorhelpdesk.com|
lockdoorherox|lockdoorherox.com|
lockdoorhq|lockdoorhq.com|
lockdoorhub|lockdoorhub.com|
lockdooriq|lockdooriq.com|
lockdoorjet|lockdoorjet.com|
lockdoorkey|lockdoorkey.com|
lockdoorlab|lockdoorlab.com|
lockdoorlabx|lockdoorlabx.com|
lockdoorlink|lockdoorlink.com|
lockdoorlite|lockdoorlite.com|
lockdoorlux|lockdoorlux.com|
lockdoormasters|lockdoormasters.com|
lockdoormax|lockdoormax.com|
lockdoormaxpro|lockdoormaxpro.com|
lockdoormaxx|lockdoormaxx.com|
lockdoormega|lockdoormega.com|
lockdoormicro|lockdoormicro.com|
lockdoormini|lockdoormini.com|
lockdoornano|lockdoornano.com|
lockdoornation|lockdoornation.com|
lockdoornet|lockdoornet.com|
lockdoornetwork|lockdoornetwork.com|
lockdoornetx|lockdoornetx.com|
lockdoornex|lockdoornex.com|
lockdoornovax|lockdoornovax.com|
lockdoornow|lockdoornow.com|
lockdooromega|lockdooromega.com|
lockdoorone|lockdoorone.com|
lockdooronex|lockdooronex.com|
lockdoorops|lockdoorops.com|
lockdooropspro|lockdooropspro.com|
lockdoorpad|lockdoorpad.com|
lockdoorpilot|lockdoorpilot.com|
lockdoorpop|lockdoorpop.com|
lockdoorprime|lockdoorprime.com|
lockdoorprimex|lockdoorprimex.com|
lockdoorpro|lockdoorpro.com|
lockdoorproedge|lockdoorproedge.com|
lockdoorprofix|lockdoorprofix.com|
lockdoorprogo|lockdoorprogo.com|
lockdoorprohub|lockdoorprohub.com|
lockdoorproline|lockdoorproline.com|
lockdoorproq|lockdoorproq.com|
lockdoorprosolutions|lockdoorprosolutions.com|
lockdoorproteam|lockdoorproteam.com|
lockdoorprotech|lockdoorprotech.com|
lockdoorprotection|lockdoorprotection.com|
lockdoorproworks|lockdoorproworks.com|
lockdoorprox|lockdoorprox.com|
lockdoorproz|lockdoorproz.com|
lockdoorquick|lockdoorquick.com|
lockdoorrapid|lockdoorrapid.com|
lockdoorrapidpro|lockdoorrapidpro.com|
lockdoorray|lockdoorray.com|
lockdoorrepairteam|lockdoorrepairteam.com|
lockdoorrescue|lockdoorrescue.com|
lockdoorresponse|lockdoorresponse.com|
lockdoorrun|lockdoorrun.com|
lockdoorsafety|lockdoorsafety.com|
lockdoorsafex|lockdoorsafex.com|
lockdoorservice|lockdoorservice.com|
lockdoorservicepro|lockdoorservicepro.com|
lockdoorservpro|lockdoorservpro.com|
lockdoorset|lockdoorset.com|
lockdoorshield|lockdoorshield.com|
lockdoorshieldx|lockdoorshieldx.com|
lockdoorshift|lockdoorshift.com|
lockdoorshort|lockdoorshort.com|
lockdoorsky|lockdoorsky.com|
lockdoorsolutions|lockdoorsolutions.com|
lockdoorsupport|lockdoorsupport.com|
lockdoorsystems|lockdoorsystems.com|
lockdoortap|lockdoortap.com|
lockdoortappro|lockdoortappro.com|
lockdoorteam|lockdoorteam.com|
lockdoortechs|lockdoortechs.com|
lockdoorunit|lockdoorunit.com|
lockdoorup|lockdoorup.com|
lockdoorusa|lockdoorusa.com|
lockdoorway|lockdoorway.com|
lockdoorworks|lockdoorworks.com|
lockdoorxtra|lockdoorxtra.com|
lockdoorzap|lockdoorzap.com|
lockdoorzen|lockdoorzen.com|
lockdoorzip|lockdoorzip.com|
lockdoorzone|lockdoorzone.com|
lockdriftus|lockdriftus.com|
lockdrillus|lockdrillus.com|
lockedgecous|lockedgecous.com|
lockedgeprous|lockedgeprous.com|
lockedgexus|lockedgexus.com|
lockexploitus|lockexploitus.com|
lockfantasyus|lockfantasyus.com|
lockfastcheapus|lockfastcheapus.com|
lockfixfreeus|lockfixfreeus.com|
lockfixinstantus|lockfixinstantus.com|
lockflashxus|lockflashxus.com|
lockflexus|lockflexus.com|
lockflowcous|lockflowcous.com|
lockforcexus|lockforcexus.com|
lockforgecous|lockforgecous.com|
lockforgexus|lockforgexus.com|
lockglobalus|lockglobalus.com|
lockgridus|wo0woc4ok48g8084ggw4840g.shlomoholdingsservicesllc.com|
lockgroupus|lockgroupus.com|
lockhijackus|lockhijackus.com|
lockindustryus|lockindustryus.com|
lockintrudeus|lockintrudeus.com|
lockjackerus|lockjackerus.com|
lockjetxus|lockjetxus.com|
lockliftxus|lockliftxus.com|
lockmintxus|lockmintxus.com|
locknetworkus|locknetworkus.com|
lockonlineus|lockonlineus.com|
lockoverrideus|lockoverrideus.com|
lockpickersus|lockpickersus.com|
lockpilotxus|lockpilotxus.com|
lockplayus|lockplayus.com|
lockprimecous|lockprimecous.com|
lockprimexus|lockprimexus.com|
lockpromodealsus|lockpromodealsus.com|
lockpromous|lockpromous.com|
lockproxus|lockproxus.com|
lockproxyus|lockproxyus.com|
lockpulsexus|lockpulsexus.com|
lockquestus|lockquestus.com|
lockrapidus|lockrapidus.com|
lockrisexus|lockrisexus.com|
lockrocketus|lockrocketus.com|
lockrouteus|lockrouteus.com|
lockrushus|lockrushus.com|
locksecretsus|locksecretsus.com|
lockservicesus|lockservicesus.com|
locksharpus|locksharpus.com|
lockshieldus|lockshieldus.com|
lockshiftprous|lockshiftprous.com|
lockshiftprousa|lockshiftprousa.com|
lockshiftxus|lockshiftxus.com|
locksmashus|locksmashus.com|
locksnapperus|locksnapperus.com|
locksnapxus|locksnapxus.com|
locksparkxus|locksparkxus.com|
lockspotus|lockspotus.com|
lockstarxus|lockstarxus.com|
lockstoreus|lockstoreus.com|
lockswiftxus|lockswiftxus.com|
lockswitchus|lockswitchus.com|
locksystemsus|locksystemsus.com|
locksystemus|locksystemus.com|
locktapperus|locktapperus.com|
locktapprous|locktapprous.com|
locktapxus|locktapxus.com|
locktigerus|locktigerus.com|
locktrackxus|locktrackxus.com|
locktrailprous|locktrailprous.com|
locktrailxus|locktrailxus.com|
locktuneprous|locktuneprous.com|
locktunexus|locktunexus.com|
lockunitxus|lockunitxus.com|
lockuniverseus|lockuniverseus.com|
lockwaveprous|lockwaveprous.com|
lockwavexus|lockwavexus.com|
lockwiseus|lockwiseus.com|
lockwolfxus|lockwolfxus.com|
lockworldus|lockworldus.com|
lockzerous|lockzerous.com|
lockzillaus|lockzillaus.com|
lockzonexus|lockzonexus.com|
masteroflocksus|masteroflocksus.com|
metrokeyteam|metrokeyteam.com|
militarylockus|militarylockus.com|
nakedlockus|nakedlockus.com|
nationallockus|nationallockus.com|
nationalsecuritylockus|nationalsecuritylockus.com|
nopaylockus|nopaylockus.com|
nuclearlockus|nuclearlockus.com|
officiallockus|officiallockus.com|
openailockus|openailockus.com|
openlocktonightus|openlocktonightus.com|
pickanylockus|pickanylockus.com|
policelockus|policelockus.com|
primekeyteam|primekeyteam.com|
prisonlockus|prisonlockus.com|
publiclockus|publiclockus.com|
publicsafetylockus|publicsafetylockus.com|
samsunglockus|samsunglockus.com|
securealllocksus|securealllocksus.com|
securitykeyservice|securitykeyservice.com|
smartkeyservice|smartkeyservice.com|
stateauthoritylockus|stateauthoritylockus.com|
statelockus|statelockus.com|
steallockus|steallockus.com|
stripelockus|stripelockus.com|
superlock123us|superlock123us.com|
teslalockus|teslalockus.com|
thekeyshopus|thekeyshopus.com|
thekeyspeople|thekeyspeople.com|
tiktoklockus|tiktoklockus.com|
toyotalockus|toyotalockus.com|
uberlockus|uberlockus.com|
ultrakeysolutions|ultrakeysolutions.com|
unlockalllocks|unlockalllocks.com|
urbankeyservicesus|urbankeyservicesus.com|
usauthoritylock|usauthoritylock.com|
vaultlockus|vaultlockus.com|
veteranskeyservices|veteranskeyservices.com|
visalockus|visalockus.com|
"""
echo 'Cloning repos...'
echo "$REPOS" | while IFS='|' read -r repo domain subfolder; do
  if [ -z "$repo" ]; then continue; fi
  echo "Cloning $repo -> $SITES_DIR/$domain"
  git clone --depth 1 "https://${GIT_AUTH}github.com/shlomoholdingsllc-ai/$repo.git" "$SITES_DIR/$domain" 2>&1 || echo "FAILED: $repo"
  rm -rf "$SITES_DIR/$domain/.git" 2>/dev/null
  if [ -n "$subfolder" ] && [ -d "$SITES_DIR/$domain/$subfolder" ]; then
    cp -r "$SITES_DIR/$domain/$subfolder/"* "$SITES_DIR/$domain/"
    rm -rf "$SITES_DIR/$domain/$subfolder"
  fi
done
nginx -g "daemon off;"
