server {
    listen 80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Serve from directory matching the Host header
    location / {
        try_files /$host/$uri /$host/ /$host/index.html /index.html =404;
    }
}